#!/bin/bash
#
# ========================================================================================
# Copyright (C) 2005-2010 UDW-SOFTWARE <http://udw.altervista.com/>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# This script will export all tables from specified db and tables in separated sql files
# it can also export the full db in a single sql file.
# =========================================================================================

if [ ! -z "$4" ]; then
	source $4
else
	# check config from same folder
	source $(dirname $0)/mysql_config 
fi

source $(dirname $0)/shared_def

# Table prefix ( to implement )
PFX=

function checkdb {
    # Check if database exists
    err=`echo "quit" | $BIN_DIRmysql$OPTS $1 2>&1`
    if [ $? != 0 ]; then
        if echo "$err" | grep -q "Access denied"; then
            echo -e "\nDATABASE $1 EXISTS BUT USER $USER DOES NOT HAVE ACCESS TO IT, ABORTING"
            exit
        fi
        echo -n "[creating $1]"
        if ! echo "CREATE DATABASE $1;" | $MYSQL$OPTS 2>/dev/null ; then
            echo -e "\nDATABASE $1 DOES NOT EXIST AND I FAILED TO CREATE IT, ABORTING"
            exit
        fi
    fi
}

function import
{
    echo "Importing $2 into $DB ..."
	if (($1 != 0)); then
		$MYSQLIMPORT$OPTS $IMPORTOPTS_TEXT $DB $2
	else
		$MYSQL$OPTS $DB <$2
		echo " done"
	fi
}

if [ ! -z "$1" ]; then 
	DB=$1; 
fi

checkdb $DB

if [ ! -z "$2" ]; then 
	tables=$(echo $2 | tr "," "\n")
fi
if [ ! -z "$3" ]; then 
	FULL=$3; 
fi

if (($FULL != 0)); then
	echo "importing full world file"
	$MYSQL$OPTS $DB < $FPATH
else
	if [ ! -z "$2" ]; then
		import "0" "$TPATH/$2.sql"
		if (($TEXTDUMPS != 0)); then
			import "1" "$TPATH/*.txt"
		fi
	else
		for x in $TPATH/*.sql; do
			import "0" "$x"
		done
		
		if (($TEXTDUMPS != 0)); then
			import "1" "$TPATH/*.txt"
		fi
	fi
fi
