#!/bin/bash
#
# ========================================================================================
# Copyright (C) 2005-2010 UDW-SOFTWARE <http://udw.altervista.com/>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# This script will export all tables from specified db and tables in separated sql files
# it can also export the full db in a single sql file.
# =========================================================================================
#
#  This script automatically dump and import sql files
#
#	syntax: ./mysql_tools <opt> <tables>
#	OPT -> dump/import   ( export / import tables )
#	TABLES -> if OPT=1 , use "," to separate table names; ex: mysql_dump "" "table1,table2..tableN". Leave blank to dump all tables.
#

function main() {
	if [ ! -z "$1" ]; then 
	 if [ "$1" == "dump" ]; then 
		./mysql_dump "" "$2" "1"
		return
	 elif [ "$1" == "import" ]; then
		if [ ! -z "$2" ]; then 
			./mysql_import 1 $2
			return
		else
			./mysql_import 0 
			return
		fi
	 fi
	fi
}

main "$1" "$2"