#!/bin/bash
#
# ========================================================================================
# Copyright (C) 2005-2010 UDW-SOFTWARE <http://udw.altervista.com/>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# This script will export all tables from specified db and tables in separated sql files
# it can also export the full db in a single sql file.
# =========================================================================================

if [ ! -z "$4" ]; then
	source $4
else
	# check config from same folder
	source ./mysql_config 
fi;

# Table prefix ( to implement )
PFX=

function in_array() {
  local x
  ENTRY=$1
  shift 1
  ARRAY=( "$@" )
  [ -z "${ARRAY}" ] && return 0
  [ -z "${ENTRY}" ] && return 0
  for x in ${ARRAY[@]}; do
    [ "${x}" == "${ENTRY}" ] && return 1
  done
  return 0
}

function import ()
{
    echo -n "Importing $1 into $DB ..."
    # Check if database exists
    err=`echo "quit" | mysql$OPTS $DB 2>&1`
    if [ $? != 0 ]; then
        if echo "$err" | grep -q "Access denied"; then
            echo -e "\nDATABASE $db EXISTS BUT USER $USER DOES NOT HAVE ACCESS TO IT, ABORTING"
            exit
        fi
        echo -n "[creating $DB]"
        if ! echo "CREATE DATABASE $DB;" | mysql$OPTS 2>/dev/null ; then
            echo -e "\nDATABASE $DB DOES NOT EXIST AND I FAILED TO CREATE IT, ABORTING"
            exit
        fi
    fi
    mysql$OPTS $DB <$1
    echo " done"
}

if [ ! -z "$1" ]; then 
	DB=$1; 
fi
if [ ! -z "$2" ]; then 
	tables=$(echo $2 | tr "," "\n")
fi
if [ ! -z "$3" ]; then 
	CREATEFULL=$3; 
fi

if (($FULL != 1)); then
	echo "importing full world file"
	mysql$OPTS $DB < $FPATH
else
	if [ ! -z "$2" ]; then
			import $TPATH/$2.sql
	else
		for x in $TPATH/*.sql; do
			import $x
		done
	fi
fi
