#!/bin/bash
#
# ========================================================================================
# Copyright (C) 2005-2010 UDW-SOFTWARE <http://udw.altervista.com/>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# This script will export all tables from specified db and tables in separated sql files
# it can also export the full db in a single sql file.
# =========================================================================================

if [ ! -z "$4" ]; then
	source "$4"
else
	# check config from same folder
	source $(dirname $0)/mysql_config 
fi

source $(dirname $0)/shared_def

if [ ! -z "$1" ]; then 
 DB=$1;
fi

#change group instead mod
#group=`ls -l tables | awk '{print $4}'`
#if [ $group != "mysql" ]; then
#    if (($CHMODE != 0)); then
#       sudo chgrp -v mysql $TPATH
#    fi
#fi

#change permissions for other users
if (($CHMODE != 0)); then
    echo "changing permissions.."
    sudo chmod -v o=rwx $TPATH
fi

if (($CLEANFOLDER!=0)); then
	rm -rv $TPATH/*
fi

if [ ! -z "$2" ]; then 
	arr=$(echo $2 | tr "," "\n")

	for T in $arr
	do
		echo "exporting "$T;
		if (($TEXTDUMPS != 1)); then
			$MYSQLDUMP$OPTS $DUMPOPTS $DB $T | sed 's$),($),\n($g' > $TPATH/$T.sql 
		else
			$MYSQLDUMP$OPTS $DUMPOPTS --tab=$TPATH/ $DB $T
		fi
	done
	
else 
	if (($TEXTDUMPS != 1)); then
		for T in `mysql$OPTS -N -B -e 'show tables from '$DB`; \
		   do 
				echo "exporting "$T; \
				$MYSQLDUMP$OPTS $DUMPOPTS $DB $T | sed 's$),($),\n($g' > $TPATH/$T.sql;
		   done;
	else
		echo "exporting "$DB;
		$MYSQLDUMP$OPTS $DUMPOPTS --tab=$TPATH/ $DB $T
	fi
fi

if [ ! -z "$3" ]; then FULL=$3; fi

if (($FULL!=0)); then   
	echo 'exporting FULL '$DB' in single file';
	$MYSQLDUMP$OPTS $DUMPOPTS $DB | sed 's$),($),\n($g' > $FPATH;
fi

