#!/bin/bash
#
#  This script automatically dump and import sql files
#
#	syntax: ./mysql_tools <opt> <tables>
#	OPT -> dump/import   ( export / import tables )
#	TABLES -> if OPT=1 , use "," to separate table names; ex: mysql_dump "" "table1,table2..tableN". Leave blank to dump all tables.
#

function main() {
	if [ ! -z "$1" ]; then 
	 if [ "$1" == "dump" ]; then 
		./mysql_dump "" "$2" "1"
		return
	 elif [ "$1" == "import" ]; then
		if [ ! -z "$2" ]; then 
			./mysql_import 1 $2
			return
		else
			./mysql_import 0 
			return
		fi
	 fi
	fi
}

main "$1" "$2"