#!/bin/bash
#
# ========================================================================================
# Copyright (C) 2005-2010 UDW-SOFTWARE <http://udw.altervista.com/>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# This script will export all tables from specified db and tables in separated sql files
# it can also export the full db in a single sql file.
# =========================================================================================

function main() {
	if [ ! -z "$1" ]; then 
		if [ "$1" == "dump" ]; then 
			./mysql_dump "$3" "$2" "$4" "$5"
			return
		elif [ "$1" == "import" ]; then
			./mysql_import "$3" "$2" "$4" "$5"
			return
		fi
	fi
}

# OPT - Tables - database - full file - config path
main "$1" "$2" "$3" "$4" "$5"