#!/bin/bash
#
# ========================================================================================
# Copyright (C) 2005-2010 UDW-SOFTWARE <http://udw.altervista.com/>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# This script will export all tables from specified db and tables in separated sql files
# it can also export the full db in a single sql file.
# =========================================================================================

MYSQL="mysql"
MYSQLIMPORT="mysqlimport"
MYSQLDUMP="mysqldump"

#empty for bash commands
WIN_BIN=0
command -v mysql >/dev/null 2>&1 || { WIN_BIN=1; }
command -v mysqlimport >/dev/null 2>&1 || { WIN_BIN=1; }
command -v mysqldump >/dev/null 2>&1 || { WIN_BIN=1; }

WIN_BIN=1
if [ `uname -s` == "Linux" ]; then
   WIN_BIN=0
else
   WIN_BIN=1 
fi;

if (($WIN_BIN != 0)); then
	MYSQL=$MT_DIR"/$MYSQL"
	MYSQLIMPORT=$MT_DIR"/$MYSQLIMPORT"
	MYSQLDUMP=$MT_DIR"/$MYSQLDUMP"
fi;

OPTS=
[ ! -z "$MYSQL_USER" ] && OPTS+=" -u $MYSQL_USER"
[ ! -z "$MYSQL_PASS" ] && OPTS+=" -p$MYSQL_PASS"
[ ! -z "$MYSQL_HOST" ] && OPTS+=" -h $MYSQL_HOST"
[ ! -z "$MYSQL_SOCK" ] && OPTS+=" -S $MYSQL_SOCK"
